name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/hn721/fgo24-be-tickitz:latest

      - name: Copy db to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 146.190.102.54
          username: hosea
          port: 9201
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: |
            db
          target: /home/hosea/deploy

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 146.190.102.54
          username: hosea
          port: 9201
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/hosea/deploy
            docker compose pull
            docker compose up -d db redis
            sleep 10  # Tunggu db ready
            docker compose run --rm migration
            docker compose up -d app
